// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA2BxfTxm215C2hsdGzGoh6u0JifXoaETo',
    appId: '1:655351264129:web:cbb324fb538f6908096e80',
    messagingSenderId: '655351264129',
    projectId: 'finder-24700',
    authDomain: 'finder-24700.firebaseapp.com',
    storageBucket: 'finder-24700.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6wiDyuF_pgVm5jzu31o3JmgSjvB4Fdzc',
    appId: '1:655351264129:android:13ec54db20b67249096e80',
    messagingSenderId: '655351264129',
    projectId: 'finder-24700',
    storageBucket: 'finder-24700.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDe3APaqVNDojyy5xASVTu6RFRHzkzQE88',
    appId: '1:655351264129:ios:dfdac9f30e1a536a096e80',
    messagingSenderId: '655351264129',
    projectId: 'finder-24700',
    storageBucket: 'finder-24700.firebasestorage.app',
    iosBundleId: 'com.example.finder',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDe3APaqVNDojyy5xASVTu6RFRHzkzQE88',
    appId: '1:655351264129:ios:dfdac9f30e1a536a096e80',
    messagingSenderId: '655351264129',
    projectId: 'finder-24700',
    storageBucket: 'finder-24700.firebasestorage.app',
    iosBundleId: 'com.example.finder',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA2BxfTxm215C2hsdGzGoh6u0JifXoaETo',
    appId: '1:655351264129:web:62e75f9ed97d8958096e80',
    messagingSenderId: '655351264129',
    projectId: 'finder-24700',
    authDomain: 'finder-24700.firebaseapp.com',
    storageBucket: 'finder-24700.firebasestorage.app',
  );
}
